import type { Metadata } from 'next'
import { Inter, Source_Code_Pro } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'

const interSans = Inter({
  subsets: ["latin"],
});

const sourceCodeMono = Source_Code_Pro({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${interSans.className} ${sourceCodeMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
