import { ThemeProvider } from '@/components/common/theme-provider'
import type { Metadata } from 'next'
import { Inter, Source_Code_Pro } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin']
})

const sourceCodeMono = Source_Code_Pro({
  variable: '--font-source-code-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${interSans.variable} ${sourceCodeMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
